[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.25"

optimizer = true
optimizer_runs = 200

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
